campusconnect/adhoc/urls.py
from django.urls import path
from django.conf.urls import url, include

app_name = "adhoc"

from .views import (
    AdhocRequestByGuest,
    AdhocRequestSubmitConf,


    AdhocHome,
    AdhocHowItWorks,
    AdhocTermsCond,
    AdhocAppChecklist,
    AdhocCompareThis,
    AdhocUseCases,
    AdhocProductDeliveryMethods,
    AdhocFAQ,

    
)


adhoc_urls = [
    # product pages 
    path("request/create", AdhocRequestByGuest.as_view(),
        name="adhoc_submit_req_now"
    ),
    path("request/submit-confirmation/<int:id>/<str:token>",
        AdhocRequestSubmitConf.as_view(),
        name="adhoc_req_sub_conf"
    ),


    # non-product pages         
    path("home",
        AdhocHome.as_view(),
        name="adhoc_home"),

    path("terms-conditions",
        AdhocTermsCond.as_view(),
        name="adhoc_terms_cond"),

    path("app-checklist",
        AdhocAppChecklist.as_view(),
        name="adhoc_checklist"),



    # prod insight
    path("how-it-works",
        AdhocHowItWorks.as_view(),
        name="adhoc_how_it_works"),
    path("product-comparison",
        AdhocCompareThis.as_view(),
        name="adhoc_compare_this"),
    path("use-cases",
        AdhocUseCases.as_view(),
        name="adhoc_use_cases"),
    path("faq",
        AdhocFAQ.as_view(),
        name="adhoc_faq"),
    path("product-delivery-methods",
        AdhocProductDeliveryMethods.as_view(),
        name="adhoc_del_meth"),
]


urlpatterns = [
    path("", include(adhoc_urls)),
]

campusconnect/campusconnect/urls.py
import debug_toolbar
from django.urls import path, include
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from django.conf import settings


from prof_candidate.views import resume_download_view

urlpatterns = [

    # app name >> adhoc
    ##############################################
    path("app/adhoc/", include('adhoc.urls')),

    # app name >> mmhauth
    ##############################################
    path('app/auth_mmh/v2/', include('mmhauth.urls')),

    # app name >> guestactions
    ##############################################
    path('app/actions/', include('guestactions.urls')),

    # app name >> mydocumentations
    ##############################################
    path('app/docs/', include('mydocumentations.urls')),

    # app name >> prof_candidate
    ##############################################
    path('app/candidate/', include('prof_candidate.urls')),

    # app name >> resumeweb
    ##############################################
    path('',    include('resumeweb.urls')),
    path('rw/', include('resumeweb.urls')),
    
    # app name >>> superadmin
    ##############################################
    path('app/superadmin/', include('superadmin.urls')),




    # debug toolbar
    # path('__debug__/', include(debug_toolbar.urls)),




    # file download
    ##############################################
    path('download/', resume_download_view, name="resume_download_link"),



]

campusconnect/prof_candidate/urls.py
from django.conf import settings
from django.urls import path
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

from resumeweb.views import PromotionalOffersView
from .views import (

    CandidateProfileHome,

    # ============= my rewards
    MyCurrentRewardOffers,
    MyEarnedCoupons,

    # ============= my orders
    OrderHistoryAll,
    OrderDetails,
    # MyInvoices,
    # InvoicePDF,
    ServiceFeedbackView,


    # ============ referral


    # ============ order cancellation
    CancelOrder_mmh,
    OrderCancellationRequestView,
    OrderCancellationDetailsView,
    CancelOrderSuccess_mmh,
    CancelOrderFailed_mmh,


    # ============= disputes
    FileDisputeWithTrackingId,
    DisputeHistory,
    DisputeDetails,
    DisputeResult,
    DisputeConfirmation,
    FileDisputeFromOrderDetails,


    # ============= resume profile
    ResumeDocView,
    ResumeFormView,
    ResumeFormEditView,
    ResumeFormTips,
    ResumeFormConfirm,
    delete_doc,

    # ============= cust comm
    CandidateMsg,
    MsgHistory,
    MsgDetails,
    MsgConfirm,


    # ============= my info
    UpdatePassView,
    AccountDeactivationView,
    AccDeactivateConfirmView,

    # ============= acct settings
    AcctSettingsHomeView,

)


app_name = 'prof_candidate'


home = [
    path(
        'home',
        CandidateProfileHome.as_view(),
        name="dashboard_homepage"
    ),

]


rewards = [
    path(
        'offers',
        MyCurrentRewardOffers.as_view(),
        name="my_current_offers"
        ),
    path(
        'earnings',
        MyEarnedCoupons.as_view(),
        name="my_earned_coupons"
    ),

]


cust_comm = [
    path('contact-us',
        CandidateMsg.as_view(),
        name="msg_submit"
    ),
    path('my-message-history',
        MsgHistory.as_view(),
        name="msg_history"
    ),
    path('my-message-detail/<int:pk>',
        MsgDetails.as_view(),
        name="msg_details"
    ),
    path('my-message-confirmation',
        MsgConfirm.as_view(),
        name="msg_confirm"
    ),

]


order_cancellation_links = [
    path('submit/request/<str:tracking_id>',           OrderCancellationRequestView.as_view(),                name="mmh_cancel_order"),
    path('request/details/<str:tracking_id>',           OrderCancellationDetailsView.as_view(),                name="mmh_cancel_order_details"),    
    path('submit/request/success/<str:tracking_id>',    CancelOrderSuccess_mmh,         name="mmh_cancel_order_success"),
    path('submit/request/failed/<str:tracking_id>',     CancelOrderFailed_mmh,          name="mmh_cancel_order_failed"),

]


my_orders = [
    path('history',                                 OrderHistoryAll,                name="order_history_all"),
    path('detail/<str:tracking_id>',                OrderDetails,                   name="order_details"),
    path('order/<str:tracking_id>/submit-feedback', ServiceFeedbackView.as_view(),    name="submit_feedback_for_order"),
        
    # path('my-invoices',                             MyInvoices.as_view(),           name="order_invoice"),
    # path('invoice-pdf/<str:tracking_id>',           InvoicePDF,                     name="invoice_pdf"),

    # mmh: removed when processing merged into pending view
    # path('history_inprocessing',                    OrderHistoryInProcessing,       name="order_history_inprocessing"),

]


my_disputes = [
    path(
        'order/file-dispute',
        FileDisputeWithTrackingId.as_view(),
        name="file_disp_with_tracking_id"
    ),
    path(
        'my-dispute-history',
        DisputeHistory.as_view(),
        name="dispute_history"
    ),
    path(
        'my-dispute-confirmation',
        DisputeConfirmation.as_view(),
        name="dispute_confirm"
    ),
    path(
        'my-dispute-details/<pk>',
        DisputeDetails.as_view(),
        name="dispute_details"
    ),
    path(
        'my-dispute-results',
        DisputeResult.as_view(),
        name="dispute_result"
    ),
    path(
        'order/<str:tracking_id>/file-dispute',
        FileDisputeFromOrderDetails.as_view(),
        name="file_dispute_from_order_details"
    ),
    # path(
    #     'order-feedback-form',
    #     OrderFeedbackView.as_view(),
    #     name="order_feedback_form"
    # ),

]


my_resume_prof = [
    path(
        'resume-upload-url',
        ResumeDocView.as_view(),
        name="resume_doc_upload_link"
    ),
    path(
        'resume-form',
        ResumeFormView.as_view(),
        name="resume_form"
    ),
    path(
        'resume-form-edit',
        ResumeFormEditView.as_view(),
        name="resume_form_edit"
    ),
    path(
        'resume-form-submission-confirm',
        ResumeFormConfirm.as_view(),
        name="resume_form_confirm"
    ),
    path(
        'resume-form-fillup-tips',
        ResumeFormTips.as_view(),
        name="resume_form_tips"
    ),
    path(
        'resume-delete/<int:doc_id>',
        delete_doc, 
        name="resume_doc_delete"
    ),
]


acct_set = [
    path(
        'home',
        AcctSettingsHomeView.as_view(),
        name="acct_set_home"
    ),

    path(
            "account-settings/update_password/", 
            UpdatePassView.as_view(), 
            name="update_password"
        ),

    # path(
    #         "account-settings/update_password/done/", 
    #         auth_views.PasswordChangeDoneView.as_view(extra_context={"msg": "Password Updated Successfully"}), 
    #         name="password_change_done"
    #     ),


    path(
        "deactivate_account",
        AccountDeactivationView.as_view(),
        name="account_deactivate"
    ),
    path(
        "deactivate_account_done",
        AccDeactivateConfirmView.as_view(),
        name="account_deactivate_done"
    )
]


urlpatterns = [
    path("", include(home)),
    path("my-orders/dispute/", include(my_disputes)),
    path("my-orders/", include(my_orders)),
    path("my-orders/cancellation/", include(order_cancellation_links)),
    path("my-resume/", include(my_resume_prof)),
    # path("referral-request/", include(referral)),
    path("my-rewards/", include(rewards)),
    path("cust-comm/", include(cust_comm)),
    path("account-settings/", include(acct_set)),
    
]

campusconnect/prof_candidate/forms/dispute.py
from django import forms
from django.forms import Textarea
from ..models import (
	DisputeClaim,
	DispCause
)
from resumeweb.models import mcart
from django.contrib.auth.models import User




class DisputeForm(forms.ModelForm):

	class Meta:
		model = DisputeClaim
		fields = "__all__"
		exclude = ('created_aganist', 'created_by',)

	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.label_suffix = ""



campusconnect/prof_candidate/views/acct_set.py
from zzz_lib.zzz_log import zzz_print
import json
from uuid import uuid4
from django.shortcuts import render
from base64 import b64decode, b64encode
from django.contrib.auth.models import User
from django.views.generic.base import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.tokens import PasswordResetTokenGenerator
from django.db import connection
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_decode
from django.http import HttpResponse, Http404, JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.core.serializers.json import DjangoJSONEncoder
from django.urls import reverse_lazy
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from django.shortcuts import redirect
from django.views.generic import UpdateView
from django.utils import timezone
from django.views.generic.edit import FormView
from django.contrib import messages

from django.views.generic import (
    ListView,
    UpdateView,
    DetailView
)
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from django.views.generic.edit import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin

from ..forms import (
    AccDeactivateForm,
    PasswordUpdateForm,
)
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth.forms import PasswordChangeForm
from prof_candidate.models import (DeactivatedAccount,)
from django.contrib.auth import update_session_auth_hash

from commonroom.myfunctions.send_email import send_email_customized
import datetime

TEMPLATE_DIR = "prof_candidate/layout/acct_settings/"




##***************************************************
class AcctSettingsHomeView(LoginRequiredMixin, TemplateView):
    template_name = TEMPLATE_DIR + "home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['section_header_1'] = 'Your Basic Information'
        context['section_header_2'] = 'Account Deactivation Form'
        return context




# password change form
##***************************************************
class UpdatePassView(LoginRequiredMixin, PasswordChangeView):
    template_name = TEMPLATE_DIR + "update_pass.html"
    success_url = reverse_lazy('prof_candidate:update_password')
    form_class = PasswordUpdateForm

    def form_valid(self, form):
        messages.success(self.request, "Password Updated Successfully")
        form.save()
        form.user = self.request.user
        subject = "Password Updated Successfully"
        email_body = "You have successfully updated Your password"        
        time = datetime.datetime.now()
        send_email_customized(self.request.user.email,subject,email_body,time)
        update_session_auth_hash(self.request, form.user)
        return super(UpdatePassView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['section_header_1'] = 'Update Your Password'
        context['section_header_2'] = 'Account Deactivation Form'
        return context




# Deactivation form submission
##***************************************************
class AccountDeactivationView(LoginRequiredMixin, CreateView):
    template_name = TEMPLATE_DIR+"acct_deactivate.html"
    form_class = AccDeactivateForm
    success_url = "deactivate_account_done"
    model = DeactivatedAccount      
    
    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.email = self.request.user.email

        # save the form 
        self.object.save()

        subject = "Account Deactivation"
        email_body = "You have deactivated your account"   
        time = datetime.datetime.now()     
        send_email_customized(self.request.user,subject,email_body,time)
        logout(self.request)

        return render(self.request,  TEMPLATE_DIR+"acct_deactivate_done.html")


    def get_form_kwargs(self, *args, **kwargs):
        kwargs = super(AccountDeactivationView, self).get_form_kwargs(*args, **kwargs)
        kwargs['email'] = self.request.user.email
        return kwargs


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['section_header_1'] = 'Deactivate Your Account'
        context['section_header_2'] = 'Account Deactivation Form'
        return context




# Confirm Deactivation View
##***************************************************
class AccDeactivateConfirmView(LoginRequiredMixin, TemplateView):
    template_name = TEMPLATE_DIR+"acct_deactivate_done.html"


campusconnect/prof_candidate/views/cust_comm.py
import datetime
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.generic import (
    ListView,
    DetailView
)
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView

from prof_candidate.models import (
    CandidateInternalMsg,
)
from zzz_lib.zzz_log import zzz_print
from ..forms import CandidateInternalMsgForm
from commonroom.myfunctions.send_email import send_email_customized


TEMPLATE_DIR = "prof_candidate/layout/cust_comm/"


# ******************************************************************************
class CandidateMsg(LoginRequiredMixin, CreateView):
    template_name = TEMPLATE_DIR + "contact-us.html"
    form_class = CandidateInternalMsgForm

    def form_valid(self, form):
        m = form.save(commit=False)
        m.created_by = self.request.user
        m.created_at = datetime.datetime.now()
        m.save()
        subject = "We are here to listen you "
        email_body = "Thank You for contacting us. Our resposible person will contact you soon"     
        time = datetime.datetime.now()   
        
        send_email_customized(self.request.user.email,subject,email_body,time)
        return HttpResponseRedirect(reverse('prof_candidate:msg_confirm'))


# ******************************************************************************
class MsgHistory(LoginRequiredMixin, ListView):
    model = CandidateInternalMsg
    template_name = TEMPLATE_DIR + "msg-history.html"

    def get_context_data(self, *, object_list=None, **kwargs):
        zzz_print("    %-28s: %s" % ("get_context_data()", ""))

        context = super().get_context_data(**kwargs)
        context["no_of_msg"] = CandidateInternalMsg.objects.filter(created_by=self.request.user).count()
        for key in context:
            zzz_print("    key %-24s: value %s" % (key, context[key]))

        return context

    def get_queryset(self):
        qs = CandidateInternalMsg.objects.filter(created_by=self.request.user)\
            .order_by('-created_at')
        return qs



# ******************************************************************************
class MsgDetails(LoginRequiredMixin, DetailView):
    model = CandidateInternalMsg
    template_name = TEMPLATE_DIR + "msg-details.html"



# ******************************************************************************
class MsgConfirm(LoginRequiredMixin, TemplateView):
    template_name = TEMPLATE_DIR + "msg_confirm.html"


campusconnect/prof_candidate/templates/prof_candidate/components/menu/acct_set.html
    <div class="card-body">

      <h5 class="fw-bolder text-uppercase">Account Settings</h5>
      <ul class="card-list list text-reset">
        <li class="list-item">
          <a class="list-link text-reset" href="{% url 'prof_candidate:acct_set_home' %}">
            Account Info
          </a>
        </li>
        <li class="list-item">
          <a class="list-link text-reset" href="{% url 'prof_candidate:update_password' %}">
            Update Password
          </a>
        </li>
        <li class="list-item">
          <a class="list-link text-reset" href="{% url 'prof_candidate:account_deactivate' %}">
            Deactivate Account
          </a>
        </li>
      </ul>

    </div>

campusconnect/prof_candidate/templates/prof_candidate/components/menu/cust_comm.html
<div class="card-body">
  <h5 class="fw-bolder text-uppercase">Communication Channel</h5>
  <ul class="card-list list text-reset">
    <li class="list-item">
      <a class="list-link text-reset" href="{% url 'prof_candidate:msg_submit' %}">
        Contact Us
      </a>
    </li>
    <li class="list-item">
      <a class="list-link text-reset" href="{% url 'prof_candidate:msg_history' %}">
        My Message History
      </a>
    </li>
  </ul>
</div>

campusconnect/prof_candidate/templates/prof_candidate/components/menu/disputes.html
<div class="card-body">
  <h5 class="fw-bolder text-uppercase">Disputes</h5>
  <ul class="card-list list text-reset">
    <li class="list-item">
      <a class="list-link text-reset" href="{% url 'prof_candidate:dispute_history' %}">
        My Dispute History
      </a>
    </li>
  </ul>
</div>

campusconnect/prof_candidate/templates/prof_candidate/components/menu/home.html
<div class="card-body">
  <h6 class="fw-bold text-uppercase">
    Account
  </h6>
</div>

campusconnect/prof_candidate/templates/prof_candidate/components/menu/main-menu.html
{% load static %}


<div class="bg-light" style="z-index:1030">
  <nav class="navbar navbar-expand-lg navbar-light py-1 bg-white">
    <div class="container-fluid">

      {% include 'resumeweb/components/menus/header/site_main_logo34.html' %}


      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarLogo"
        aria-controls="navbarLogo" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Collapse Section -->
      <div class="nav me-lg-auto mb-2 justify-content-center mb-md-0 collapse navbar-collapse" id="navbarLogo">

        <!-- Toggler button -->
        <div> <button class="col-2 navbar-toggler ms-auto bg-danger d-block d-sm-none d-md-block d-lg-none  "
            type="button" data-bs-toggle="collapse" data-bs-target="#navbarLogo" aria-controls="navbarLogo"
            aria-expanded="false" aria-label="Toggle navigation">
            <i class="fe fe-x"></i>
          </button></div>


        <!-- items -->
        {% include 'resumeweb/components/menus/header/collapse-section-items.html' %}

      </div>


    </div>
  </nav>
</div>

campusconnect/prof_candidate/templates/prof_candidate/components/menu/orders.html
<div class="card-body">
  <h5 class="fw-bolder text-uppercase">My Orders</h5>
  <ul class="card-list list text-reset">
    <li class="list-item">
      <a class="list-link text-reset" href="{% url 'prof_candidate:order_history_all' %}">
        My Order History
      </a>
    </li>
  </ul>
</div>


{% comment "Optional note" %}
MMH: removing this view as it is being merged into pending view.
MMH: pending view renamed to processing.
<li class="list-item">
  <a class="list-link text-reset" href="{% url 'prof_candidate:order_history_inprocessing' %}">
    Processing
  </a>
</li>
{% endcomment %}

campusconnect/prof_candidate/templates/prof_candidate/components/menu/referral.html
<div class="card-body">

  <h6 class="fw-bold text-uppercase">
    Referral Request
  </h6>
  <ul class="card-list list text-reset">
    <li class="list-item">
      <a class="list-link text-reset" href="{% url 'prof_candidate:my_current_offers' %}">
        Submit Request
      </a>
    </li>
    <li class="list-item">
      <a class="list-link text-reset" href="{% url 'prof_candidate:my_earned_rewards' %}">
        Terms & Conditions
      </a>
    </li>
  </ul>

</div>

campusconnect/prof_candidate/templates/prof_candidate/components/menu/resume.html
<div class="card-body">
  <h5 class="fw-bolder text-uppercase">Resume & Profile</h5>
  <ul class="card-list list text-reset">
    <li class="list-item">
      <a class="list-link text-reset" href="{% url 'prof_candidate:resume_doc_upload_link' %}">
        Resume Doc File
      </a>
    </li>
    <li class="list-item">
      <a class="list-link text-reset" href="{% url 'prof_candidate:resume_form' %}">
        Resume Form
      </a>
    </li>
  </ul>
</div>

campusconnect/prof_candidate/templates/prof_candidate/components/menu/rewards.html
<div class="card-body">

  <h5 class="fw-bolder text-uppercase">My Rewards</h5>

  <ul class="card-list list text-reset">
    <li class="list-item">
      <a class="list-link text-reset" href="{% url 'prof_candidate:my_current_offers' %}">
        Current Offers
      </a>
    </li>
    <li class="list-item">
      <a class="list-link text-reset" href="{% url 'prof_candidate:my_earned_coupons' %}">
        My Coupons
      </a>
    </li>
  </ul>

</div>