campusconnect/adhoc/urls.py
from django.urls import path
from django.conf.urls import url, include

app_name = "adhoc"

from .views import (
    AdhocRequestByGuest,
    AdhocRequestSubmitConf,


    AdhocHome,
    AdhocHowItWorks,
    AdhocTermsCond,
    AdhocAppChecklist,
    AdhocCompareThis,
    AdhocUseCases,
    AdhocProductDeliveryMethods,
    AdhocFAQ,

    
)


adhoc_urls = [
    # product pages 
    path("request/create", AdhocRequestByGuest.as_view(),
        name="adhoc_submit_req_now"
    ),
    path("request/submit-confirmation/<int:id>/<str:token>",
        AdhocRequestSubmitConf.as_view(),
        name="adhoc_req_sub_conf"
    ),


    # non-product pages         
    path("home",
        AdhocHome.as_view(),
        name="adhoc_home"),

    path("terms-conditions",
        AdhocTermsCond.as_view(),
        name="adhoc_terms_cond"),

    path("app-checklist",
        AdhocAppChecklist.as_view(),
        name="adhoc_checklist"),



    # prod insight
    path("how-it-works",
        AdhocHowItWorks.as_view(),
        name="adhoc_how_it_works"),
    path("product-comparison",
        AdhocCompareThis.as_view(),
        name="adhoc_compare_this"),
    path("use-cases",
        AdhocUseCases.as_view(),
        name="adhoc_use_cases"),
    path("faq",
        AdhocFAQ.as_view(),
        name="adhoc_faq"),
    path("product-delivery-methods",
        AdhocProductDeliveryMethods.as_view(),
        name="adhoc_del_meth"),
]


urlpatterns = [
    path("", include(adhoc_urls)),
]

campusconnect/campusconnect/urls.py
import debug_toolbar
from django.urls import path, include
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from django.conf import settings


from prof_candidate.views import resume_download_view

urlpatterns = [

    # app name >> adhoc
    ##############################################
    path("app/adhoc/", include('adhoc.urls')),

    # app name >> mmhauth
    ##############################################
    path('app/auth_mmh/v2/', include('mmhauth.urls')),

    # app name >> guestactions
    ##############################################
    path('app/actions/', include('guestactions.urls')),

    # app name >> mydocumentations
    ##############################################
    path('app/docs/', include('mydocumentations.urls')),

    # app name >> prof_candidate
    ##############################################
    path('app/candidate/', include('prof_candidate.urls')),

    # app name >> resumeweb
    ##############################################
    path('',    include('resumeweb.urls')),
    path('rw/', include('resumeweb.urls')),
    
    # app name >>> superadmin
    ##############################################
    path('app/superadmin/', include('superadmin.urls')),




    # debug toolbar
    # path('__debug__/', include(debug_toolbar.urls)),




    # file download
    ##############################################
    path('download/', resume_download_view, name="resume_download_link"),



]

campusconnect/guestactions/urls.py
from django.conf import settings
from django.urls import path
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

app_name = "guestactions"

from .views import (
    ContactUsGuestView,
    CheckOrderStatusView,
    ProductReviewGuestView,
    feedback_submit_confirmation_view,
    ProductSearchResultsView,
    InviteFriendsView,
    InviteFriendsThankyou,
    SiteSurveyView,
    SurveyThankyouView,
)

urls_sitesurvey = [ 
    path("help-center/action/site-survey",      
        SiteSurveyView.as_view(),       
        name="submit_site_survey_as_guest"
    ),
    path("help-center/action/site-survey/thankyou",  
        SurveyThankyouView.as_view(),   
        name="site_survey_thankyou"
    ),
]

urls_productsearch = [    
    path("", ProductSearchResultsView.as_view(), name="product_search_link"),   
]

urls_orderstatuscheck = [
    path("check-order-status", CheckOrderStatusView.as_view(), name="check_my_order_status"),
]

urls_contactus = [
    path("help-center/action/contact-us", ContactUsGuestView.as_view(), name="contact_us_guest"),
]

urls_invitefriends = [
    path("help-center/action/invite-friends",           InviteFriendsView,      name="invite_friends_link"),
    path("help-center/action/invite-friends/thankyou",  InviteFriendsThankyou,  name="invite_friends_thankyou"),
]

urls_productreview = [
    path("help-center/action/product-review",           ProductReviewGuestView, name="product_feedback_by_guest_link"),
    path("help-center/action/product-review/thankyou",  feedback_submit_confirmation_view, name="feedback_submit_confirmation_view"),

]

urlpatterns = [
    path("",            include(urls_productsearch)),
    path("",            include(urls_orderstatuscheck)),
    path("",            include(urls_contactus)),
    path("",            include(urls_invitefriends)),
    path("",            include(urls_productreview)),
    path("",            include(urls_sitesurvey)),

]

campusconnect/resumeweb/urls.py
from django.conf.urls import url, include
from django.urls import path

# product
from .urls_products import (
    usvisa_urls,
    dialect_url,
    intprep_urls,
    exp180_urls,
    # mmr_eval_urls,
    identity_url,
    staircase_urls,
    strat_sol_urls
)

# product details
from .views.products import (
    USVisaProdDetails_ajax,
    RoleBasedServiceDetails_ajax,
    ProgLangServiceProdDetails_ajax,
    IntPrepProdDetails_ajax,
    Exp180DetailView_ajax,
    # EvalDetailView_ajax,
    ProfLevelServiceDetails_ajax,
    StratSolProdDetails_ajax,
)

# cart
from .views import (
    mmh_CartHome,
    mmh_CartFileUpload,
    # mmh_CartUserLogin,
    mmh_CartGuestLogin,
    mmh_CartLoginPage,
    mmh_CartLoginOrGuestSuccess,
    mmh_CartPurchaseSuccess,
    rwCartAjaxView_contents,
    rwCartAjaxView_carticon,
    rwCartAjaxView_emptycart,
    rwCartAjaxView_removebymodelnameandid,
    rwCartAjaxView_addproductver2,
    rwCartAjaxView_removeproductver2,
    # rwCartAjaxView_applycoupontocart,
    # rwCartAjaxView_unapplycoupontocart,
    # rwCartAjaxView_applycoupon,

)

# paypal
from .views import (
    vcreate,
    vcapture,
)

# user permissions
from .views import (
    vug_failed_test,
)

# general
from .views import(
    HomePageView,
    Page404View,
    AboutUsView,
    # top news
    Covid19ResponseView,
    BLMResponseView,
    PromotionalOffersView,
    ThisIsBeta,
    UsOnlySupport,
    # help center
    HelpCenterHome,
    MemberBenefitsView,
)



site_general_urls = [
    path("", 
        HomePageView.as_view(), 
        name="site_homepage_url"
    ),
    path("home/", 
        HomePageView.as_view(), 
        name="site_homepage_url"
    ),
    path("product-docs/all",
        AboutUsView.as_view(),
        name="about_us"
    ),
    path("page-404-view", 
        Page404View.as_view(), 
        name="page_404_view"
    ),

]



############################## news section
topnews_urls = [
    path("covid19-response", 
        Covid19ResponseView.as_view(), 
        name="covid19_res_url"
    ),
    path("how-we-tackle-racial-injudtice", 
        BLMResponseView.as_view(), 
        name="blm_page"
    ),
    path("promotional-offers", 
        PromotionalOffersView.as_view(), 
        name="promo_offers_page"
    ),
    path("us-only", 
        UsOnlySupport.as_view(), 
        name="us_only_support"
    ),    
    path("beta", 
        ThisIsBeta.as_view(), 
        name="this_is_beta"
    ),        
]



footer_urls = [
    # help center section
    ############################## 
    path("help-center/home",
        HelpCenterHome.as_view(),
        name="cust_service_home"
    ),
    path("help-center/membership-benefits",
        MemberBenefitsView.as_view(),
        name="mem_ben_url"
    ),    
]

all_product_urls = [
    # products that use cart
    path("exp180/",                     include(exp180_urls)),          # mprod_exp180
    # path("eval/",                     include(mmr_eval_urls)),        # mprod_eval
    path("dialogue/",                   include(intprep_urls)),         # mprod_intprep
    path("staircase/",                  include(staircase_urls)),       # mprod_proflevel
    path("dialect/",                    include(dialect_url)),          # mprod_proglang
    path("identity/",                   include(identity_url)),         # mprod_rolebased
    path("strategy/",                   include(strat_sol_urls)),       # mprod_strategy
    path("bandwidth/",                  include(usvisa_urls)),          # mprod_visabased
]

# cart urls
mmh_cart_urls = [
    path("cart/home/mmh",                                       mmh_CartHome,                               name="mmh_carthome"),
    path("cart/upload",                                         mmh_CartFileUpload,                         name="mmh_cartfileupload"),
    # path("checkout/sign-in/mmh/userlogin",                      mmh_CartUserLogin,                          name="mmh_cartuserlogin"),
    path("checkout/sign-in/mmh",                                mmh_CartLoginPage,                          name="mmh_cartcheckout"),
    path("checkout/sign-in/mmh/loginorguestsuccess",            mmh_CartLoginOrGuestSuccess,                name="mmh_cartloginorguestsuccess"),
    path("checkout/sign-in/mmh/guestlogin",                     mmh_CartGuestLogin,                         name="mmh_cartguestlogin"),
    path("checkout/success/<str:paypaltransaction_id>",         mmh_CartPurchaseSuccess,                    name="mmh_cartpurchasesuccess"),
]

# cart AJAX urls
mmh_cart_urls_ajax = [
    path("contents",                                            rwCartAjaxView_contents,                name="rwCartAjaxView_contents"),
    path("carticon",                                            rwCartAjaxView_carticon,                name="rwCartAjaxView_carticon"),
    path("emptycart",                                           rwCartAjaxView_emptycart,               name="rwCartAjaxView_emptycart"),
    path("removebymodelnameandid",                              rwCartAjaxView_removebymodelnameandid,  name="rwCartAjaxView_removebymodelnameandid"),
    path("addproductver2",                                      rwCartAjaxView_addproductver2,          name="rwCartAjaxView_addproductver2"),
    path("removeproductver2",                                   rwCartAjaxView_removeproductver2,       name="rwCartAjaxView_removeproductver2"),
    # path("applycoupontocart/<str:string32>",                    rwCartAjaxView_applycoupontocart,       name="rwCartAjaxView_applycoupontocart"),
    # path("unapplycoupontocart/<str:string32>",                  rwCartAjaxView_unapplycoupontocart,     name="rwCartAjaxView_unapplycoupontocart"),
    # path("applycoupon",                                         rwCartAjaxView_applycoupon,             name="rwCartAjaxView_applycoupon"),
]

# paypal_urls
mmh_vpaypal_urls = [
    path('vcreate', vcreate, name="vpaypal_vcreate"),
    path('vcapture/<order_id>', vcapture, name="vpaypal_vcapture"),
]

# cart ajax detail product views
mmh_cart_detail_ajax_product_views = [
    path("mprod_exp180/<int:id>",       Exp180DetailView_ajax,              name="exp180_detail_view_link_ajax"),
    path("mprod_intprep/<int:id>",      IntPrepProdDetails_ajax,            name="intprep_detail_view_link_ajax"),
    path("mprod_proflevel/<int:id>",    ProfLevelServiceDetails_ajax,       name="proflevel_detail_view_link_ajax"),
    path("mprod_proglang/<int:id>",     ProgLangServiceProdDetails_ajax,    name="proglang_detail_view_link_ajax"),
    path("mprod_rolebased/<int:id>",    RoleBasedServiceDetails_ajax,       name="rolebased_detail_view_link_ajax"),
    path("mprod_strategy/<int:id>",     StratSolProdDetails_ajax,           name="strategy_detail_view_link_ajax"),
    path("mprod_visabased/<int:id>",    USVisaProdDetails_ajax,             name="visabased_detail_view_link_ajax"),
]


# user permissions
vusergroup_views = [
    path("failedtest/<str:testname>/<str:viewname>/<str:optionalmessage>",  vug_failed_test,     name="vug_failed_test"),
    path("failedtest/<str:testname>/<str:viewname>",                        vug_failed_test,     name="vug_failed_test"),
]


## final url declaration
########################
## GENERAL STUFF
SITE_GENERAL       = [path("",                 include(site_general_urls)),]
FOOTER            = [path("",                 include(footer_urls)),]

TOPNEWS            = [path("news/",            include(topnews_urls)),]


## CART + PayPal
MMH_CART       = [path("cart/",            include(mmh_cart_urls)),]
MMH_CART_AJAX  = [path("cart_ajax/",       include(mmh_cart_urls_ajax)),]
MMH_AJAX_DETAIL     = [path("ajax_detail/",     include(mmh_cart_detail_ajax_product_views)),]
PAYPAL         = [path("vpaypal/",         include(mmh_vpaypal_urls)),]
## PRODUCT PAGES
PRODUCT        = [path("service/",         include(all_product_urls)),]
## USER PERMISSIONS
USERGROUP      = [path("vug/",             include(vusergroup_views)),]


urlpatterns =   SITE_GENERAL
urlpatterns +=  FOOTER
urlpatterns +=  TOPNEWS

urlpatterns +=  MMH_CART
urlpatterns +=  MMH_CART_AJAX
urlpatterns +=  MMH_AJAX_DETAIL
urlpatterns +=  PAYPAL
urlpatterns +=  PRODUCT
urlpatterns +=  USERGROUP

campusconnect/resumeweb/models/buyer_list.py
import uuid
from django.db import models


class BuyerListGuest(models.Model):
    email 		    = models.CharField		(max_length=300)
    reguser         = models.BooleanField   (default=False)
    transaction_id  = models.CharField      (max_length=100, default="00000000000")
    created         = models.DateTimeField  (auto_now_add=True, help_text="timestamp of creation")
    updated         = models.DateTimeField  (auto_now=True, help_text="timestamp of last update")

    class Meta:
        verbose_name 		= 'Buyer Email List'
        verbose_name_plural = 'Buyer Email List'


    def __str__(self):
        return "{}->{}".format(self.email, self.reguser)

campusconnect/resumeweb/models/mbase_deliveryoption.py
from zzz_lib.zzz_log import zzz_print
from django.db import models
from .mbase_sku import mbase_sku

# All products that have delivery options inherit from this class.
# ******************************************************************************
class mbase_deliveryoption(mbase_sku):
    name                            = models.CharField      (max_length=2000)
    listprice                       = models.DecimalField   (default=0.99, decimal_places=2, max_digits=1000,)
    price                           = models.DecimalField   (default=0.99, decimal_places=2, max_digits=1000)
    description                     = models.CharField      (max_length=2000, blank=True, null=True)
    hours_to_cancel_after_payment   = models.IntegerField   (default=168)
    # Next field must always be greater than or equal to previous field.
    hours_to_deliver_after_payment  = models.IntegerField   (default=336)

    # Following fields ARE NOT fields that should be saved/used/stored in Database
    ndb_checked             = False

    # --------------------------------------------------------------------------
    class Meta:
        abstract = True
        ordering = ['price']   # Auto sort queries by lowest price first.

    # --------------------------------------------------------------------------
    def __str__(self):
        return f"{self.name}"

    # --------------------------------------------------------------------------
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)















campusconnect/resumeweb/models/mbase_prod.py
from zzz_lib.zzz_log import zzz_print
from django.db import models
from .mbase_sku import mbase_sku

# ******************************************************************************
# All products that use the cart system inherit from this class.
# ******************************************************************************
class mbase_prod(mbase_sku):
    listprice           = models.DecimalField(default=0.99, decimal_places=2, max_digits=100,)
    saleprice           = models.DecimalField(default=0.99, decimal_places=2, max_digits=100,)

    # --------------------------------------------------------------------------
    class Meta:
        abstract = True

    # --------------------------------------------------------------------------
    # Child classes should override this method if they require post purchase processing
    # Note: post purchase processing is dispatched to a non blocking thread so be careful what is done in there.
    def post_purchase_processing(self, request, imcompleted_purchase):
        zzz_print("    %-28s: %s" % ("post_purchase_processing", "fall through to mbase_prod"))
        pass



















campusconnect/resumeweb/models/mprod_exp180_deliveryoption.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.db import models
from .mprod_exp180 import mprod_exp180
from .mbase_deliveryoption import mbase_deliveryoption

# ******************************************************************************
class mprod_exp180_deliveryoption(mbase_deliveryoption):
    products                = models.ManyToManyField(to=mprod_exp180)
    class_threeletterprefix = "dd3"

    class Meta:
        verbose_name_plural = "01_Exp180_DelivOption_List"















campusconnect/resumeweb/templates/resumeweb/layout/general/about-us.html
{% extends 'resumeweb/layout/primary_layout.html' %}


{% block body_contents %}


  {% include 'resumeweb/pg-contents/about-us-pg/opening-banner.html' %}





  {% include 'resumeweb/pg-contents/about-us-pg/section1.html' %}  


  {% include 'resumeweb/pg-contents/about-us-pg/section2.html' %}


  {% include 'resumeweb/pg-contents/about-us-pg/section3.html' %}




  {% include 'resumeweb/pg-contents/about-us-pg/section5.html' %}


  {% include 'resumeweb/pg-contents/about-us-pg/section6.html' %}


  {% include 'resumeweb/pg-contents/about-us-pg/section7.html' %}






{% endblock %}

campusconnect/resumeweb/templates/resumeweb/layout/general/blm.html
{% extends 'resumeweb/layout/primary_layout.html' %}


{% block body_contents %}


  {% include 'resumeweb/pg-contents/blm.html' %}




{% endblock %}

campusconnect/resumeweb/templates/resumeweb/layout/general/covid19.html
{% extends 'resumeweb/layout/primary_layout.html' %}


{% block body_contents %}


  {% include 'resumeweb/pg-contents/covid-resp-pg/opening-banner.html' %}



  {% include 'resumeweb/pg-contents/covid-resp-pg/resp1.html' %}

  {% include 'resumeweb/pg-contents/covid-resp-pg/resp2.html' %}

  {% include 'resumeweb/pg-contents/covid-resp-pg/resp3.html' %}




    <section class="pt-4 pt-md-11">
      <div class="container">
        <div class="row align-items-center">
          <div class="col-12 col-md-5 order-md-2">

            <!-- Image -->
            <img src="assets/img/illustrations/illustration-1.png" class="img-fluid mb-6 mb-md-0" alt="...">

          </div>
          <div class="col-12 col-md-7 order-md-1">

            <!-- Heading -->
            <h2 class="">
              Are you in the job market looking for a job or job change with
              <span class="text-primary">International Student VISA (F1)?</span>
            </h2>

            <!-- Text -->
            <p class="lead text-muted mb-0">
              Helping and guiding job seekers with international student visa
              is one of our top priorities. That's whay we have a whole new service line for this category.
              Through Bandwidth we are offerings services to Five VISA categories such as CPT, OPT. Learn more 
              about <a class="text-warning" href="{% url 'usvisa_home' %}">Bandwidth</a>
            </p>

          </div>
        </div>
      </div>
    </section>



    <section class="pb-8 pt-7 pb-md-11 pt-md-10">
      <div class="container">
        <div class="row">
          <div class="col-12">

            <!-- Heading -->
            <h2 class="mb-0">
              Why Signup with Us ?
            </h2>

            <!-- Text -->
            <p class="mb-5 text-muted">
              These can be split into smaller grid sizes, though we recommend half or thirds
            </p>

          </div>
        </div> <!-- / .row -->
        <div class="row">
          <div class="col-12 col-md-6 d-flex">

            <!-- Card -->
            <div class="card mb-6">

              <!-- Image -->
              <a class="card-img-top" href="#!">
                <img src="assets/img/photos/photo-28.jpg" alt="..." class="img-fluid">
              </a>

              <a class="card-body" href="#!">
                <h3>
                  Photo on Top + 50% Width.
                </h3>
                <p class="mb-0 text-muted">
                  The markup for vertical articles is the same for a half and thirds split, it's controlled with columns.
                </p>
              </a>

              <a class="card-meta" href="#!">
                <hr class="card-meta-divider">
                <h6 class="text-uppercase text-muted me-2 mb-0">
                  Learn More
                </h6>
              </a>

            </div>

          </div>
          <div class="col-12 col-md-6 d-flex">

            <!-- Card -->
            <div class="card pt-14 bg-cover overlay overlay-secondary overlay-80 text-white shadow-light-lg mb-6" style="background-image: url(assets/img/covers/cover-17.jpg);">

              <!-- Body -->
              <a class="card-body mt-auto" href="#!">
                <h3 class="mt-auto">
                  some title goes here778
                </h3>
                <p class="mb-0 text-white-80">
                  Background photos are super easy to add and overlays can be added with utilities for legibility.
                </p>
              </a>

              <a class="card-meta" href="#!">
                <hr class="card-meta-divider bg-white-20">
                <h6 class="text-uppercase text-white-80 me-2 mb-0">
                  Learn More
                </h6>
              </a>

            </div>

          </div>
        </div>
        
      </div>
    </section>



    <section class="pb-8 pt-7 pb-md-11 pt-md-10">
      <div class="container">
        <div class="row">
          <div class="col-12">

            <!-- Heading -->
            <h2 class="mb-0">
              Why Signup with US ?
            </h2>

            <!-- Text -->
            <p class="mb-5 text-muted">
              These can be split into smaller grid sizes, though we recommend half or thirds
            </p>

          </div>
        </div>

        <div class="row">
          <div class="col-12 col-md-6 col-lg-4">

            <!-- Card -->
            <div class="card mb-6 mb-lg-0 shadow-light-lg border border-warning">

              <div class="card-body">
                <h3>
                  This is the topic sentense we need
                </h3>
                <p class="mb-0 text-muted">
                  The markup for this card is identical to that for the 50% Width article above.
                </p>
              </div>

              <div class="card-meta">
                <hr class="card-meta-divider bg-white-20">
                <div class="avatar avatar-sm me-2">
                  <img src="assets/img/avatars/avatar-1.jpg" alt="..." class="avatar-img rounded-circle">
                </div>
                <h6 class="text-uppercase text-white-80 me-2 mb-0">
                  <a href="">Know More37</a>
                </h6>
              </div>

            </div>

          </div>
          <div class="col-12 col-md-6 col-lg-4">
            <div class="card mb-6 mb-lg-0 shadow-light-lg border border-dark">
              <div class="card-body">
                <h3>
                  This is the topic sentense we need
                </h3>
                <p class="mb-0 text-muted">
                  The markup for this card is identical to that for the 50% Width article above.
                </p>
              </div>

              <div class="card-meta">
                <hr class="card-meta-divider">
                <div class="avatar avatar-sm me-2">
                  <img src="assets/img/avatars/avatar-1.jpg" alt="..." class="avatar-img rounded-circle">
                </div>
                <h6 class="text-uppercase text-muted me-2 mb-0">
                  <a href="">Know More29</a>
                </h6>
              </div>

            </div>

          </div>
          <div class="col-12 col-lg-4">
            <div class="card shadow-light-lg">
              <a class="card-body my-auto" href="#!">
                <h3 class="mt-auto">
                  All Text Card.
                </h3>
                <p class="mb-0 text-muted">
                  Notice how this card stays the same height as its siblings and this text is vertically centered (at desktop sizes). This keeps layouts looking consistent no matter what type of content occupies each sibling card.
                </p>
              </a>
              <div class="card-meta">
                <hr class="card-meta-divider">
                <div class="avatar avatar-sm me-2">
                  <img src="assets/img/avatars/avatar-1.jpg" alt="..." class="avatar-img rounded-circle">
                </div>
                <h6 class="text-uppercase text-muted me-2 mb-0">
                  <a href="">Know More3</a>
                </h6>
              </div>
            </div>
          </div>

        </div>
      </div>
    </section>


{% endblock %}

campusconnect/resumeweb/templates/resumeweb/layout/general/faq.html
<div class="mb-6">
	{% include 'mydocumentations/productdocs/pg-contents/faq/bg.html' %}
</div>

<div class="mb-6">
	{% include 'mydocumentations/productdocs/pg-contents/faq/ques-ans.html' %}
</div>	

campusconnect/resumeweb/templates/resumeweb/layout/general/gpdm.html
<div class="mb-6">
	{% include 'resumeweb/pg-contents/gpdm/bg.html' %}
</div>

<div class="mb-6">
	{% include 'resumeweb/pg-contents/gpdm/user_types.html' %}
</div>

<div class="mb-6">
	{% include 'resumeweb/pg-contents/gpdm/deliverables.html' %}
</div>

<div class="mb-6">
	{% include 'resumeweb/pg-contents/gpdm/delivery_ensurity_policy.html' %}
</div>

campusconnect/resumeweb/templates/resumeweb/layout/general/help-center-home.html
{% extends 'resumeweb/layout/primary_layout.html' %}


{% block opening_banner %}
  {% include 'resumeweb/pg-contents/help-center-home/1-opening-banner.html' %}
{% endblock %}


{% block body_contents %}

  {% include 'resumeweb/pg-contents/help-center-home/body.html' %}
  
{% endblock %}

campusconnect/resumeweb/templates/resumeweb/layout/general/member-benefits.html
{% extends 'resumeweb/layout/primary_layout.html' %}


{% block body_contents %}


  {% include 'resumeweb/pg-contents/helpCenterHomePg/1-opening-banner.html' %}


  {% include 'resumeweb/components/breadcrumb/contact-us.html' %}
  

  {% include 'resumeweb/pg-contents/mem-ben/sample1.html' %}



{% endblock %}

campusconnect/resumeweb/templates/resumeweb/layout/general/promo-offers-2.html
{% extends 'resumeweb/layout/primary_layout.html' %}


{% block body_contents %}



  {% include 'resumeweb/pg-contents/promo-offers/opening-banner.html' %}



  <section class="py-8 py-md-11">
    <div class="container">
      <div class="row align-items-center justify-content-between">
        {% include 'resumeweb/pg-contents/promo-offers/offer-1.html' %}
      </div>
    </div>
  </section>


  <section class="py-8 py-md-11">
    <div class="container">
      <div class="row align-items-center justify-content-between">
        {% include 'resumeweb/pg-contents/promo-offers/offer-2.html' %}
      </div>
    </div>
  </section>











{% endblock %}

campusconnect/resumeweb/templates/resumeweb/layout/general/search-global-v2.html
{% extends 'resumeweb/layout/base_prod_list.html' %}


{% block meta %}
  <title>Search | Global | Resumenalyzer</title>
  <meta content="" name="descriptison">
  <meta content="" name="keywords">
{% endblock %}


{% block leftside_contents %}
  add the following
  1. links of all services for all products
{% endblock %}


{% block service_list %}
  {% include "resumeweb/pg-contents/search-module/global-search1234.html" %}
{% endblock %}

campusconnect/resumeweb/templates/resumeweb/layout/general/this-is-beta.html
{% extends 'resumeweb/layout/primary_layout.html' %}


{% block body_contents %}


<section class="py-8 py-md-4">
  <div class="container">
    <div class="mx-auto p-3 py-md-5">
      <h1>Welcome to resumenalyzer <span class="badge bg-secondary">BETA</span></h1>
      <p class="col-md-8">
        We are glad to release our BETA version after a 
        regorous R&D of more than three and half years. 
        The objective was to help guide the 
        US job seekers in both Spring and Fall season of 2022. 
      </p>
    </div>
  </div>
</section>  



<section class="py-8 py-md-4">
  <div class="container">
    <div class="mx-auto p-3 py-md-5">
        <div class="row">
          <div class="col-md-6">
            <h2>Current features</h2>
            <p>Resumenalyzer</p>
            <ul class="icon-list">
              <li>
                <a href="{% url 'guestactions:check_my_order_status' %}">Order Status Check</a>
              </li>
              <li>
                <a href="{% url 'guestactions:product_feedback_by_guest_link' %}">Product Feedback</a>
              </li>
              <li>
                Order Status Update
              </li>              
            </ul>
            <p>Candidate Profile</p>
            <ul class="icon-list">
              <li>
                <a href="{% url 'prof_candidate:dashboard_homepage' %}">Candiate Dashboard</a>
              </li>
              <li>
                <a href="{% url 'prof_candidate:dashboard_homepage' %}">Order History</a>
              </li>              
              <li>
                Dispute Filling
              </li>
              <li>
                Order Cancellation
              </li>              
            </ul>            
          </div>
        </div>    
    </div>
  </div>
</section>



<section class="py-8 py-md-4">
  <div class="container">
    <div class="mx-auto p-3 py-md-5">
        <div class="row">
          <div class="col-md-6">
            <h2>Upcoming features</h2>
            <p>
              In our next major release, we hope to add some interesting features such as 
            </p>
            <ul class="icon-list">
              <li class="text-muted">Profile Readiness Analysis</li>
            </ul>
          </div>
        </div>
    </div>
  </div>
</section>  







{% endblock %}