campusconnect/adhoc/urls.py
from django.urls import path
from django.conf.urls import url, include

app_name = "adhoc"

from .views import (
    AdhocRequestByGuest,
    AdhocRequestSubmitConf,


    AdhocHome,
    AdhocHowItWorks,
    AdhocTermsCond,
    AdhocAppChecklist,
    AdhocCompareThis,
    AdhocUseCases,
    AdhocProductDeliveryMethods,
    AdhocFAQ,

    
)


adhoc_urls = [
    # product pages 
    path("request/create", AdhocRequestByGuest.as_view(),
        name="adhoc_submit_req_now"
    ),
    path("request/submit-confirmation/<int:id>/<str:token>",
        AdhocRequestSubmitConf.as_view(),
        name="adhoc_req_sub_conf"
    ),


    # non-product pages         
    path("home",
        AdhocHome.as_view(),
        name="adhoc_home"),

    path("terms-conditions",
        AdhocTermsCond.as_view(),
        name="adhoc_terms_cond"),

    path("app-checklist",
        AdhocAppChecklist.as_view(),
        name="adhoc_checklist"),



    # prod insight
    path("how-it-works",
        AdhocHowItWorks.as_view(),
        name="adhoc_how_it_works"),
    path("product-comparison",
        AdhocCompareThis.as_view(),
        name="adhoc_compare_this"),
    path("use-cases",
        AdhocUseCases.as_view(),
        name="adhoc_use_cases"),
    path("faq",
        AdhocFAQ.as_view(),
        name="adhoc_faq"),
    path("product-delivery-methods",
        AdhocProductDeliveryMethods.as_view(),
        name="adhoc_del_meth"),
]


urlpatterns = [
    path("", include(adhoc_urls)),
]

campusconnect/campusconnect/urls.py
import debug_toolbar
from django.urls import path, include
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from django.conf import settings


from prof_candidate.views import resume_download_view

urlpatterns = [

    # app name >> adhoc
    ##############################################
    path("app/adhoc/", include('adhoc.urls')),

    # app name >> mmhauth
    ##############################################
    path('app/auth_mmh/v2/', include('mmhauth.urls')),

    # app name >> guestactions
    ##############################################
    path('app/actions/', include('guestactions.urls')),

    # app name >> mydocumentations
    ##############################################
    path('app/docs/', include('mydocumentations.urls')),

    # app name >> prof_candidate
    ##############################################
    path('app/candidate/', include('prof_candidate.urls')),

    # app name >> resumeweb
    ##############################################
    path('',    include('resumeweb.urls')),
    path('rw/', include('resumeweb.urls')),
    
    # app name >>> superadmin
    ##############################################
    path('app/superadmin/', include('superadmin.urls')),




    # debug toolbar
    # path('__debug__/', include(debug_toolbar.urls)),




    # file download
    ##############################################
    path('download/', resume_download_view, name="resume_download_link"),



]

campusconnect/mydocumentations/urls.py
from django.conf import settings
from django.urls import path
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

app_name = "mydocumentations"

from .views import (
    CompareAllServices,
    AllServices,
    AllPrimeServices,
    AllSeconServices,
    GeneralFaq,
)

urls_productdocs = [

    path("product-docs/all",
        AllServices.as_view(),
        name="all_services_link"
    ),
    path("product-docs/universal",
        AllPrimeServices.as_view(),
        name="all_prime_services_link"
    ),
    path("product-docs/proficiency",
        AllSeconServices.as_view(),
        name="all_secon_services_link"
    ),
    path("product-docs/product-feature-matrix",
        CompareAllServices.as_view(),
        name="compare_all_services_link"
    ),
    path("product-docs/faq/general",
        GeneralFaq.as_view(),
        name="faq_gen"
    ),

]

from .views import (
    TermsofUse,
    PrivacyPolicy,
    DoNotSellMyInfo,
    RefundPolicyCancel,
    RefundPolicyDispute,
    CookiePolicy,
    LegalPolicy,
    PaymentPolicy,
    SecurityPolicy, 

)

urls_legalpolicydocs = [

    path("cookie-policy",
        CookiePolicy.as_view(),
        name="cookie_policy"
    ),    
    path("donot-sell-info",
        DoNotSellMyInfo.as_view(),
        name="dont_sell_info"
    ),

    path("terms-of-use",
        TermsofUse.as_view(),
        name="terms_of_use"
    ),
    path("privacy-policy",
        PrivacyPolicy.as_view(),
        name="privacy_policy"
    ),

    path("cancel-and-refund-policy",
        RefundPolicyCancel.as_view(),
        name="cancel_policy"
    ),
    
    path("dispute-and-refund-policy",
        RefundPolicyDispute.as_view(),
        name="dispute_policy"
    ),
    path("payment-policy",
        PaymentPolicy.as_view(),
        name="payment_policy"
    ),

    path("security-policy",
        SecurityPolicy.as_view(),
        name="security_policy"
    ),

]

urlpatterns = [
    path("productdocs/", include(urls_productdocs)),
    path("legaldocs/",   include(urls_legalpolicydocs)),
]

campusconnect/adhoc/views/adhoc.py
import os
import datetime
import copy
import json

# ******************************************************************************
from django.contrib import messages
import datetime
from django.urls import reverse_lazy
from django.http import HttpResponse, HttpResponseRedirect
from django.template.loader import (
    render_to_string,
    get_template
)
from django.template import Context
from django.core.mail import send_mail, BadHeaderError
from django.utils.html import strip_tags
from django.views.generic.edit import FormMixin
from resumeweb.send_email_v2 import send_email
from resumeweb.get_coupon_code import generate_coupon_code
import logging
logger = logging.getLogger(__name__)

from django.db.models import Q
from django.views.generic.base import TemplateView, View
from django.shortcuts import render, reverse
from django.shortcuts import get_object_or_404
from django.views.generic import (
    ListView,
    # UpdateView,
    # DetailView
)
from django.conf import settings
from django.views.generic.edit import CreateView
from django.contrib.messages.views import SuccessMessageMixin

from zzz_lib.zzz_log import zzz_print

from ..models import (
    AdhocRequestModel
)

from resumeweb.models import (mprod_exp180)

from ..forms import (
    AdhocRequestForm,
)

prod_comp_data_adhoc = [
    ('1', 'You can order for a service that suits your needs'),
    ('2', 'We intent to respond to your request within 48 regular hours'),
    ('3', 'You will be informed if we are not able to provide a solution to your needs'),
    ('4', 'You can order for a service that suits your needs'),
    ('5', 'Submitting an Adhoc Request is free, you will be asked to make payment only if we provide with your service'),
    ('6', 'Service delivery within as minimum as 6 hours'),
]

from resumeweb.product_selection import (
    generate_product_list,

)

from systemops.fetch_data import (
    fetch_data_faq
)

from systemops.fetch_data import fetch_data_ta


PATH_ROOT               = os.path.join(settings.BASE_DIR)
PATH_PRODUCT_LAYOUT     = 'adhoc/layout/'
PATH_PRODUCT_COMPONENT  = 'adhoc/templates/adhoc/components/'
TEMP_DIR_EMAIL          = 'adhoc/email_templates/adhoc/'

PRODUCT_LINE            = 'adhoc'
PRODUCT_SLOGAN          = 'add slogan for adhoc'

    
# homepage
# ***************************************************************
class AdhocHome(ListView):
    template_name = PATH_PRODUCT_LAYOUT+"homepg.html"
    queryset      = mprod_exp180.objects.all() #.filter(adhoc_get_started='yes')

    def get_context_data(self, **kwargs):
        context = super(AdhocHome, self).get_context_data()

        context['product_line'] = PRODUCT_LINE
        context['ta_list'] = fetch_data_ta(PRODUCT_LINE)
        context['pg_layout_type'] = 'homepg'
        return context



# This is adhoc sub req page
# ***************************************************************
class AdhocRequestByGuest(CreateView):
    template_name   = PATH_PRODUCT_LAYOUT+"request/create.html"
    form_class      = AdhocRequestForm
    model           = AdhocRequestModel


    def form_valid(self, form, **kwargs):

        adhocReq = form.save(commit=False)
        adhocReq.id = datetime.datetime.now().strftime('%f') 
        given_email = form.cleaned_data['email']
        adhocReq.save()

        # generate coupon code
        coupon_code_dict = generate_coupon(product_liked="mprod_adhoc")
        print(coupon_code_dict)
        

        email_address = given_email
        self.request.session['user_email'] = given_email
        subject = 'Adhoc Request Confirmation'+' #'+str(adhocReq.id)
        msg='thanks for your resume submission'
        change_notice ='resume upload at adhoc'
        submission_time = datetime.datetime.now()
        submission_id = adhocReq.id                 # random number

        send_email(email_address,
                    subject,msg,
                    change_notice, 
                    submission_time, 
                    submission_id, 
                    coupon_code_dict,
                    
                )
        
        return super(AdhocRequestByGuest, self).form_valid(form)


    def form_invalid(self, form, **kwargs):
        return HttpResponse('form_invalid is called')

    def get_success_url(self, **kwargs):
        token = '12665240228767'
        return reverse_lazy('adhoc_req_sub_conf', 
            kwargs={'id':self.object.pk, 'token':token}
        )

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     logger.warning("line116>>>homepage get context")
    #     context = {
    #         'proflevel_list': mprod_proflevel.objects.all().order_by('levelname'),
    #         'strategysol_list': mprod_strategy.objects.all(),
    #         'proglang_list': mprod_proglang.objects.distinct('langname'),
    #         'rolebased_list': mprod_rolebased.objects.distinct('rolename'),
    #         'app_version': "1.0",           # settings.APP_VERSION_RW,
    #         'form_guest_resume': self.get_form()
    #     }

    #     return context


# ******************************************************************************
class AdhocRequestSubmitConf(View):
    template_name = PATH_PRODUCT_LAYOUT + "request/" + "conf-1.html"

    def get(self, request, *args, **kwargs):
        adhocReq = get_object_or_404(mprod_adhoc, id=kwargs['id'])

        context = {
                'submission_id':            adhocReq.id,
                'date_time':                adhocReq.created,
                'email_address_list':       [adhocReq.email],
                'electronic_delivery_email':adhocReq.email,
                'task':                     'Adhoc Service Request',
            }
        return render(request, self.template_name, context)


# ******************************************************************************
# terms and conditions
class AdhocTermsCond(TemplateView):
    template_name = PATH_PRODUCT_LAYOUT+"terms-cond.html"


# ******************************************************************************
# app checklist
class AdhocAppChecklist(TemplateView):
    template_name = PATH_PRODUCT_LAYOUT+"app-checklist.html"


# ******************************************************************************
# how it works
class AdhocHowItWorks(TemplateView):
    template_name = PATH_PRODUCT_LAYOUT + "prod_ins_pg.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context = {
            'product_line': PRODUCT_LINE,
            'prod_slogan': PRODUCT_SLOGAN,
            'common_items': True,

            'pg_header': 'How it works',
            'how_it_works_section': True
        }
        return context


# use cases
# ******************************************************************************
class AdhocUseCases(ListView):
    template_name = PATH_PRODUCT_LAYOUT + "prod_ins_pg.html"

    def get_queryset(self):
        return mprod_exp180.objects.all().filter(level='adhoc_get_started')

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        context = {
            'product_line': PRODUCT_LINE,
            'prod_slogan': PRODUCT_SLOGAN,
            'common_items': True,

            'ta_list': fetch_data_ta(PRODUCT_LINE),
            'pg_header': 'Use Cases',
            'use_cases_section': True,
        }  
        return context


# product Comparison
# ******************************************************************************
class AdhocCompareThis(TemplateView):
    template_name = "resumeweb/layout/base_prod_comparison_v2.html"

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)

        prod_comp_data = [i[1] for i in prod_comp_data_adhoc]
        prod_list_others = generate_product_list(PRODUCT_LINE)

        context = {
            'prod_comp_data': prod_comp_data,
            'prod_list_others': prod_list_others,
            'product_line': PRODUCT_LINE,
            'prod_slogan': PRODUCT_SLOGAN,
            'common_items': True,
            'pg_header': 'Product Comparison',
            'prod_comp_section': True,

        } 
        return context


# ******************************************************************************
# deliver method
class AdhocProductDeliveryMethods(TemplateView):
    template_name = PATH_PRODUCT_LAYOUT + "prod_ins_pg.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context = {
            'product_line': PRODUCT_LINE,
            'prod_slogan': PRODUCT_SLOGAN,
            'common_items': True,

            'pg_header': 'Product Delivery Methods',
            'gen_pdm_section': True
        }
        return context


# ******************************************************************************
# product faq
class AdhocFAQ(TemplateView):
    template_name = PATH_PRODUCT_LAYOUT + "prod_ins_pg.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context = {
            'product_line': PRODUCT_LINE,
            'prod_slogan': PRODUCT_SLOGAN,
            'common_items': True,

            'pg_header': 'FAQs',
            'adhoc_faq_section': True,
            'questions_answers': fetch_data_faq(PRODUCT_LINE)
        }

        return context

campusconnect/mydocumentations/views.py
from .views_legalpolicydocs.views import *
from .views_productdocs.views import *

campusconnect/mydocumentations/views_productdocs/views.py
from datetime import datetime

from django.db.models import Q
from itertools import chain

# from haystack.query import SearchQuerySet 
import datetime
from django.conf import settings
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import ListView
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView

from zzz_lib.zzz_log import zzz_print
from django.conf import settings


TEMP_DIR_PRODUCT_DOCS   = 'mydocumentations/productdocs/layout/'


import datetime
from django.http import HttpResponse


# product docs / all services
##########################################
class AllServices(TemplateView):
    template_name = TEMP_DIR_PRODUCT_DOCS + "services_all.html"


# product docs / univ
##########################################
class AllPrimeServices(TemplateView):
    template_name = TEMP_DIR_PRODUCT_DOCS + "universal.html"


# product docs / proficiency
##########################################
class AllSeconServices(TemplateView):
    template_name = TEMP_DIR_PRODUCT_DOCS + "proficiency.html"


# FAQ / general
##########################################
class GeneralFaq(TemplateView):
    template_name = TEMP_DIR_PRODUCT_DOCS + "faq-general.html"


# product comparison
##########################################
class CompareAllServices(TemplateView):
    template_name = TEMP_DIR_PRODUCT_DOCS + "product-feature-matrix.html"

campusconnect/mydocumentations/templates/mydocumentations/productdocs/pg-contents/universal/adhoc.html
{% load static %}


<div class="row mb-4 mb-md-4 p-5">
    <div class="col-auto">
        <div class="icon-circle bg-primary text-white">
        <i class="fe fe-users"></i>
        </div>
    </div>
    <div class="col ms-n4">
        <h2 class="fw-bold mb-0">
        Adhoc
        </h2>
        <p class="fs-lg text-reset mb-0">
        product tagline
        </p>
    </div>
    <div class="col-auto">
        <a href="{% url 'adhoc:adhoc_home' %}" class="btn btn-primary-soft rounded-0">
            Product Home
        </a>          
    </div>                    
</div>

<p>
Adhoc service is designed to meet a job seeker's personal need 
if they are not covered through Exp180 services. We will request our 
customer to fillup a quick form, and our customer support team 
will respond accordingly as quickly as possible. 

</p>
<p>
<h3 class="fw-bold">
Background
</h3>
</p>

<ul>
<li>
    At the foremost, the strength of a job search candidate's 
    overall profile is being primarily judged by 
    the presentation and contents of his or her resume.

</li>                    
<li class="mt-4">
    Simply put, the format of a resume signals 
    a lot of insightful information than a candidate could think of 
    to the key figures
    in the job market such as Recruiter, Hiring Manager, Tech Lead. 

</li>
<li class="mt-4">
    Before he or she is 
    getting selcted for an interview call, 
    a candidate's resume is being reviewed by the key personnels 
    (of job market)
    different ways or from a wide range of angles which as a 
    candidate you must pass.
</li>
</ul>

<p>
<h3 class="fw-bold">
Key features
</h3>
</p>

<ul>
<li>
Adhoc service is a two fold workflow. 
First, you (a customer) will submit a service request form, and 
you need to wait until our customer support response to your
request.

Once you receive a reponse from us, you either may need to 
purchase a service, or act accordingly as instructed in the email.
</li>

<li class="mt-4">
        Our dedicated Adhoc request customer service team will review the request,
        and will respond to the request accordingly. Within the response,
        our customer support team may send a direct Exp180 service which will
        suffice the customer's need, or they will create a particular service 
        and will send the link to purchase the service to the customer.

</li>                    
<li class="mt-4">
Based on our current workload, the initial reponse time for an Adhoc service request is
usually 6 (Six) hours. Becasuse we work 24x7, not only in regular business hour
like 9 to 5.
</li>
</ul>
</p>

<p>
<h3 class="fw-bold">
Use cases
</h3>
</p>
<ul class="list-unstyled mb-7">
<li class="d-flex">
    <div class="badge badge-rounded-circle bg-success-soft mt-1 me-4">
    <i class="fe fe-check"></i>
    </div>
    <p>
        It is quite possible that a customer may overlook the service he or she 
        needs offered by Exp180 services. For many reasons, they may fail to 
        choose the suitable service from Exp180 service list.

    </p>
</li>
<li class="d-flex">
    <div class="badge badge-rounded-circle bg-success-soft mt-1 me-4">
    <i class="fe fe-check"></i>
    </div>
    <p>
    When a job search candidate runs out of options from the 
    Exp180 service list, he or she needs to submit an Adhoc service request.
    
    </p>
</li>

</ul>

<blockquote class="blockquote pb-10">
    <p class="h2 mb-0 text-center text-primary-desat">
    “Some marketing slogan for ref prog Services”
    </p>
</blockquote>


campusconnect/mydocumentations/templates/mydocumentations/productdocs/pg-contents/universal/dialogue.html
{% load static %}


<div class="row mb-4 mb-md-4 p-5">
    <div class="col-auto">
      <div class="icon-circle bg-primary text-white">
        <i class="fe fe-users"></i>
      </div>
    </div>
    <div class="col ms-n4">
      <h2 class="fw-bold mb-0">
        Dialogue
      </h2>
      <p class="fs-lg text-reset mb-0">
        product tagline
      </p>
    </div>
    <div class="col-auto">
        <a href="{% url 'intprep_all_services' %}" class="btn btn-primary-soft rounded-0">
          Product Home
        </a>          
    </div>                    
</div>

<p>
    Dialogue services are created in order to provide with 360 degree solutions
    for your upcoming technical and non-technical interview in any sized IT company.

    We take a copy of your most uptodate resume and analysis your overall profile,
    then we decide which are the question most likely to face.

</p>

<p>
    <h3 class="fw-bold">
    Key features
    </h3>
</p>
<ul>
    <li>
    Pricing of the Dialogue services is reasonable. Our objective is to provide the job applicants with the best possible toolskeep the services 
    within the reach of job search candidates from different 
    walks of life such as student, currently unemployed, or 
    on duty people.
    </li>
    <li class="mt-4">
    Dialogue services are quickly deliverable. We work round the clock, across the globe 
    in oder to make sure that we can deliver our customer orders
      as quickly as possible so that they donot have to think about
     clock and calendar.
    </li>
    <li class="mt-4">
        Dialogue services offer a wide range of solutions. Our objective
        is to make sure that our services are applicable and 
        equally effective to various scenarios 
    with a view to help remove the 
    bottlenecks of a job search journey.
    </li>
</ul>


<p>
    <h3 class="fw-bold">
    Use cases
    </h3>
</p>
<ul>
    <li class="mt-4">
        Who are looking for job in several IT positions such as 
            Software Enginner, 
            Mobile Application Developer,
            Systems Engineer,
            Database Administrator and many more.
    </li>
    <li class="mt-4">
        Job search candidate who is preparing for
            an upcoming technical phone interview,
            face to face interview,
            video interview
    </li>                  
</ul>

<blockquote class="blockquote pb-10">
    <p class="h2 mb-0 text-center text-primary-desat">
        “Some marketing slogan for ref prog Services”
    </p>
</blockquote>

campusconnect/mydocumentations/templates/mydocumentations/productdocs/pg-contents/universal/exp180.html
{% load static %}


<div class="row mb-6 mb-md-6 p-5">
    <div class="col-auto">
      <div class="icon-circle bg-primary text-white">
        <i class="fe fe-users"></i>
      </div>
    </div>
    <div class="col ms-n4">
      <h2 class="fw-bold mb-0">
        Exp180
      </h2>
      <p class="fs-lg text-reset mb-0">
        product tagline
      </p>
    </div>
    <div class="col-auto">
        <a href="{% url 'exp180_services_all' %}" class="btn btn-primary-soft rounded-0">
          Product Home
        </a>          
    </div>                    
</div>

<p>
    Exp180, an abbreviation of Express180, is a collection of services 
    that aim to solve the most common challenges
    faced by the job search candidates for getting
    selected in an interview.

</p>
<p>
    <h3 class="fw-bold">
    Background
    </h3>
</p>

<ul>
    <li>
        At the foremost, the strength of a job search candidate's 
        overall profile is being primarily judged by 
        the presentation and contents of his or her resume.

    </li>                    
    <li class="mt-4">
        Simply put, the format of a resume signals 
        a lot of insightful information than a candidate could think of 
        to the key figures
        in the job market such as Recruiter, Hiring Manager, Tech Lead. 

    </li>
    <li class="mt-4">
        Before he or she is 
        getting selcted for an interview call, 
        a candidate's resume is being reviewed by the key personnels 
        (of job market)
        different ways or from a wide range of angles which as a 
        candidate you must pass.
    </li>
</ul>




<p>
    <h3 class="fw-bold">Key features</h3>
</p>
<ul>
    <li>
    Exp180 services are very affordable. Our objective is to keep the services 
    within the reach of job search candidates from different 
    walks of life such as student, currently unemployed, or 
    on duty people.
    </li>
    <li class="mt-4">
    Exp180 services are quickly deliverable. We work round the clock, across the globe 
    in oder to make sure that we can deliver our customer orders
      as quickly as possible so that they donot have to think about
     clock and calendar.
    </li>
    <li class="mt-4">
        Exp180 services offer a wide range of solutions. Our objective
        is to make sure that our services are applicable and 
        equally effective to various scenarios 
    with a view to help remove the 
    bottlenecks of a job search journey.
    </li>
</ul>




<p>
    <h3 class="fw-bold">
    Use cases
    </h3>
</p>
<ul>
    <li class="mt-4">
        Who are looking for job in several IT positions such as 
            Software Enginner, 
            Mobile Application Developer,
            Systems Engineer,
            Database Administrator and many more.
    </li>
    <li class="mt-4">
        When a job search candidate is struggling 
            to get interview calls from a hiring manager or technical lead.
    </li>
    <li class="mt-4">
        When a job search candidate is frustrated becasuse his or her 
        resume is getting rejected for almost every position they applicaed for.
    </li>
    <li class="mt-4">
        When a job search candidate is left out of any feedback 
        after a technical interview, and the recruiter couldnot say 
        anything why he/she wasnot selected for the position.

    </li>                    
</ul>

<blockquote class="blockquote pb-10">
    <p class="h2 mb-0 text-center text-primary-desat">
        “Some marketing slogan for ref prog Services”
    </p>
</blockquote>

campusconnect/mydocumentations/templates/mydocumentations/productdocs/pg-contents/universal/intro.html
{% load static %}


<div class="col-12 col-md">
    <blockquote class="blockquote text-center mb-0">
      <p class="mb-5 mb-md-7">{% include 'mydocumentations/productdocs/pg-contents/intro-msg-univ.html' %}</p>
    </blockquote>
</div> 

<div class="row align-items-center py-5 border-top border-bottom">
  <p class="py-1 text-center">
    <span class="badge bg-secondary-soft">
      <span class="h6 text-uppercase fw-bold">Exp180</span>
    </span>
    <span class="badge bg-secondary-soft">
      <span class="h6 text-uppercase fw-bold">Adhoc</span>
    </span>
  </p>
</div>

campusconnect/mydocumentations/templates/mydocumentations/productdocs/pg-contents/universal/link-to-other.html
{% load static %}


<div class="border text-center">
    <div class="card border border-secondary">
        <div class="card-body">
            <h3 class="text-uppercase fw-bold">Universal Services</h3>
            <p class="mb-5 fs-lg text-muted">
                We work on everything from physical products to digital experiences and are looking forward to hearing from you.
            </p>
            <p>
                <a class="btn btn-secondary btn-sm w-50" href="{% url 'mydocumentations:all_prime_services_link' %}">
                Show Details <i class="fe fe-arrow-right ms-2"></i>
                </a>
            </p>
        </div>
    </div>
</div>